name: Filestore Image Build workflow
on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'backend/core-services/egov-filestore/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Set Version from Branch
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Use branch name as version, replacing '/' with '-'
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION=$(echo "${VERSION}" | sed 's|/|-|g')
          else
            VERSION="latest"  # Default version if not a tag or branch
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Git commit_hash for service
        run: |
          commit_hash=$(git log -1 --pretty=format:%H -- backend/core-services/egov-filestore)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      # Login to Docker Container Registry
      - name: Login to Docker Container Registry
        run: docker login -u selcohub -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image for egov-filestore
        run: |
          docker build --build-arg WORK_DIR="backend/core-services/egov-filestore" -t selcohub/egov-filestore:${{ env.VERSION }}-${{ env.commit_hash }} -f build/maven/Dockerfile .
          docker push selcohub/egov-filestore:${{ env.VERSION }}-${{ env.commit_hash }}

      - name: Build and Push Docker image for egov-filestore-Db
        run: |
          docker build  -t selcohub/egov-filestore-db:${{ env.VERSION }}-${{ env.commit_hash }} -f  Dockerfile .
          docker push selcohub/egov-filestore-db:${{ env.VERSION }}-${{ env.commit_hash }}
        working-directory: backend/core-services/egov-filestore/src/main/resources/db
