name: Meghalaya-UI Image Build workflow
on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'frontend/micro-ui/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      # Login to Docker Container Registry
      - name: Login to Docker Container Registry
        run: docker login -u selcohub -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Version from Tag or Branch
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}  # Use tag name for version
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Use branch name as version, replacing '/' with '-'
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION=$(echo "${VERSION}" | sed 's|/|-|g')
          else
            VERSION="latest"  # Default version if not a tag or branch
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Git commit_hash for service
        run: |
          commit_hash=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Build and Push Docker image for Meghalaya-ui
        run: |
          docker build --build-arg PUBLIC_PATH="/meghalaya-ui/"  -t selcohub/meghalaya-ui:${{ env.VERSION }}-${{ env.commit_hash }} -f  web/docker/testfile/Dockerfile .
          docker push selcohub/meghalaya-ui:${{ env.VERSION }}-${{ env.commit_hash }}
        working-directory: frontend/micro-ui

  Workflow_Trigger:
    if: startsWith(github.ref, 'refs/heads/develop')
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Trigger Deployment Pipeline
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/Selco-Foundation/DIGIT-DevOps/actions/workflows/Dev.yaml/dispatches \
          -d '{"ref":"Selco-Dev"}'
